# coding: utf-8

"""
    StorageGRID Management API v3

    REST API for managing StorageGRID deployments. Copyright (c) 2021 NetApp, Inc. All Rights Reserved  # noqa: E501

    OpenAPI spec version: 3.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.node_health_response import NodeHealthResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestNodeHealthResponse(unittest.TestCase):
    """NodeHealthResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNodeHealthResponse(self):
        """Test NodeHealthResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.node_health_response.NodeHealthResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
