# coding: utf-8

"""
    StorageGRID Management API v3

    REST API for managing StorageGRID deployments. Copyright (c) 2021 NetApp, Inc. All Rights Reserved  # noqa: E501

    OpenAPI spec version: 3.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import netapp_client
from netapp_client.models.ilm_policies_list_response import IlmPoliciesListResponse  # noqa: E501
from netapp_client.rest import ApiException


class TestIlmPoliciesListResponse(unittest.TestCase):
    """IlmPoliciesListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIlmPoliciesListResponse(self):
        """Test IlmPoliciesListResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.ilm_policies_list_response.IlmPoliciesListResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
