# coding: utf-8

"""
    StorageGRID Management API v3

    REST API for managing StorageGRID deployments. Copyright (c) 2021 NetApp, Inc. All Rights Reserved  # noqa: E501

    OpenAPI spec version: 3.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.config_management import ConfigManagement  # noqa: E501
from swagger_client.rest import ApiException


class TestConfigManagement(unittest.TestCase):
    """ConfigManagement unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConfigManagement(self):
        """Test ConfigManagement"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.config_management.ConfigManagement()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
