# coding: utf-8

"""
    StorageGRID Management API v3

    REST API for managing StorageGRID deployments. Copyright (c) 2021 NetApp, Inc. All Rights Reserved  # noqa: E501

    OpenAPI spec version: 3.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.objects_api import ObjectsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestObjectsApi(unittest.TestCase):
    """ObjectsApi unit test stubs"""

    def setUp(self):
        self.api = ObjectsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_grid_object_metadata_post(self):
        """Test case for grid_object_metadata_post

        Retrieves metadata for an object  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
