# coding: utf-8

"""
    StorageGRID Management API v3

    REST API for managing StorageGRID deployments. Copyright (c) 2021 NetApp, Inc. All Rights Reserved  # noqa: E501

    OpenAPI spec version: 3.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.regions_api import RegionsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRegionsApi(unittest.TestCase):
    """RegionsApi unit test stubs"""

    def setUp(self):
        self.api = RegionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_grid_regions_get(self):
        """Test case for grid_regions_get

        Lists configured regions  # noqa: E501
        """
        pass

    def test_grid_regions_put(self):
        """Test case for grid_regions_put

        Change the regions used by the grid  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
