# coding: utf-8

"""
    StorageGRID Management API v3

    REST API for managing StorageGRID deployments. Copyright (c) 2021 NetApp, Inc. All Rights Reserved  # noqa: E501

    OpenAPI spec version: 3.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.endpoint_domain_names_api import EndpointDomainNamesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestEndpointDomainNamesApi(unittest.TestCase):
    """EndpointDomainNamesApi unit test stubs"""

    def setUp(self):
        self.api = EndpointDomainNamesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_grid_domain_names_get(self):
        """Test case for grid_domain_names_get

        Lists endpoint domain names  # noqa: E501
        """
        pass

    def test_grid_domain_names_put(self):
        """Test case for grid_domain_names_put

        Change the endpoint domain names  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
