# coding: utf-8

"""
    StorageGRID Management API v3

    REST API for managing StorageGRID deployments. Copyright (c) 2021 NetApp, Inc. All Rights Reserved  # noqa: E501

    OpenAPI spec version: 3.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import netapp_client
from netapp_client.api.grid_passwords_api import GridPasswordsApi  # noqa: E501
from netapp_client.rest import ApiException


class TestGridPasswordsApi(unittest.TestCase):
    """GridPasswordsApi unit test stubs"""

    def setUp(self):
        self.api = GridPasswordsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_grid_change_provisioning_passphrase_get(self):
        """Test case for grid_change_provisioning_passphrase_get

        Retrieves the status of the provisioning passphrase change  # noqa: E501
        """
        pass

    def test_grid_change_provisioning_passphrase_post(self):
        """Test case for grid_change_provisioning_passphrase_post

        Changes the provisioning passphrase  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
