# coding: utf-8

"""
    StorageGRID Management API v3

    REST API for managing StorageGRID deployments. Copyright (c) 2021 NetApp, Inc. All Rights Reserved  # noqa: E501

    OpenAPI spec version: 3.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import netapp_client
from netapp_client.models.grid_health_topology_response import GridHealthTopologyResponse  # noqa: E501
from netapp_client.rest import ApiException


class TestGridHealthTopologyResponse(unittest.TestCase):
    """GridHealthTopologyResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGridHealthTopologyResponse(self):
        """Test GridHealthTopologyResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.grid_health_topology_response.GridHealthTopologyResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
