# coding: utf-8

"""
    StorageGRID Management API v3

    REST API for managing StorageGRID deployments. Copyright (c) 2021 NetApp, Inc. All Rights Reserved  # noqa: E501

    OpenAPI spec version: 3.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.recovery_package_api import RecoveryPackageApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRecoveryPackageApi(unittest.TestCase):
    """RecoveryPackageApi unit test stubs"""

    def setUp(self):
        self.api = RecoveryPackageApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_grid_recovery_package_post(self):
        """Test case for grid_recovery_package_post

        Downloads the Recovery Package  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
