# coding: utf-8

"""
    StorageGRID Management API v3

    REST API for managing StorageGRID deployments. Copyright (c) 2021 NetApp, Inc. All Rights Reserved  # noqa: E501

    OpenAPI spec version: 3.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.expansion_api import ExpansionApi  # noqa: E501
from swagger_client.rest import ApiException


class TestExpansionApi(unittest.TestCase):
    """ExpansionApi unit test stubs"""

    def setUp(self):
        self.api = ExpansionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_grid_expansion_delete(self):
        """Test case for grid_expansion_delete

        Cancels the expansion procedure and resets all user configuration of expansion grid nodes   # noqa: E501
        """
        pass

    def test_grid_expansion_expand_post(self):
        """Test case for grid_expansion_expand_post

        Executes the expansion procedure, adding configured grid nodes to the grid  # noqa: E501
        """
        pass

    def test_grid_expansion_get(self):
        """Test case for grid_expansion_get

        Retrieves the status of the current expansion procedure  # noqa: E501
        """
        pass

    def test_grid_expansion_start_post(self):
        """Test case for grid_expansion_start_post

        Initiates the expansion procedure, allowing configuration of the expansion grid nodes   # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
