# coding: utf-8

"""
    StorageGRID Management API v3

    REST API for managing StorageGRID deployments. Copyright (c) 2021 NetApp, Inc. All Rights Reserved  # noqa: E501

    OpenAPI spec version: 3.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import netapp_client
from netapp_client.api.erasure_coding_api import ErasureCodingApi  # noqa: E501
from netapp_client.rest import ApiException


class TestErasureCodingApi(unittest.TestCase):
    """ErasureCodingApi unit test stubs"""

    def setUp(self):
        self.api = ErasureCodingApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_grid_ec_profiles_get(self):
        """Test case for grid_ec_profiles_get

        Lists EC profiles  # noqa: E501
        """
        pass

    def test_grid_schemes_get(self):
        """Test case for grid_schemes_get

        Lists EC schemes  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
