# coding: utf-8

"""
    StorageGRID Management API v3

    REST API for managing StorageGRID deployments. Copyright (c) 2021 NetApp, Inc. All Rights Reserved  # noqa: E501

    OpenAPI spec version: 3.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import netapp_client
from netapp_client.api.accounts_api import AccountsApi  # noqa: E501
from netapp_client.rest import ApiException


class TestAccountsApi(unittest.TestCase):
    """AccountsApi unit test stubs"""

    def setUp(self):
        self.api = AccountsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_grid_accounts_cache_get(self):
        """Test case for grid_accounts_cache_get

        Lists cached Storage Tenant Accounts  # noqa: E501
        """
        pass

    def test_grid_accounts_get(self):
        """Test case for grid_accounts_get

        Lists Storage Tenant Accounts  # noqa: E501
        """
        pass

    def test_grid_accounts_id_change_password_post(self):
        """Test case for grid_accounts_id_change_password_post

        Changes the root user password for the Storage Tenant Account  # noqa: E501
        """
        pass

    def test_grid_accounts_id_delete(self):
        """Test case for grid_accounts_id_delete

        Deletes a single Storage Tenant Account  # noqa: E501
        """
        pass

    def test_grid_accounts_id_get(self):
        """Test case for grid_accounts_id_get

        Retrieves a single Storage Tenant Account  # noqa: E501
        """
        pass

    def test_grid_accounts_id_patch(self):
        """Test case for grid_accounts_id_patch

        Updates a single Storage Tenant Account  # noqa: E501
        """
        pass

    def test_grid_accounts_id_put(self):
        """Test case for grid_accounts_id_put

        Replaces a single Storage Tenant Account  # noqa: E501
        """
        pass

    def test_grid_accounts_id_usage_get(self):
        """Test case for grid_accounts_id_usage_get

        Gets the storage usage information for the Storage Tenant Account  # noqa: E501
        """
        pass

    def test_grid_accounts_post(self):
        """Test case for grid_accounts_post

        Creates a new Storage Tenant Account  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
