# coding: utf-8

"""
    StorageGRID Management API v3

    REST API for managing StorageGRID deployments. Copyright (c) 2021 NetApp, Inc. All Rights Reserved  # noqa: E501

    OpenAPI spec version: 3.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.list_alert_notification_receivers_response import ListAlertNotificationReceiversResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestListAlertNotificationReceiversResponse(unittest.TestCase):
    """ListAlertNotificationReceiversResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListAlertNotificationReceiversResponse(self):
        """Test ListAlertNotificationReceiversResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.list_alert_notification_receivers_response.ListAlertNotificationReceiversResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
