# coding: utf-8

"""
    StorageGRID Management API v3

    REST API for managing StorageGRID deployments. Copyright (c) 2021 NetApp, Inc. All Rights Reserved  # noqa: E501

    OpenAPI spec version: 3.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AccountNoId(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'capabilities': 'list[str]',
        'policy': 'PolicyAccount'
    }

    attribute_map = {
        'name': 'name',
        'capabilities': 'capabilities',
        'policy': 'policy'
    }

    def __init__(self, name=None, capabilities=None, policy=None):  # noqa: E501
        """AccountNoId - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._capabilities = None
        self._policy = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if capabilities is not None:
            self.capabilities = capabilities
        if policy is not None:
            self.policy = policy

    @property
    def name(self):
        """Gets the name of this AccountNoId.  # noqa: E501

        the descriptive name specified for the account (This name is for display only and might not be unique.)  # noqa: E501

        :return: The name of this AccountNoId.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this AccountNoId.

        the descriptive name specified for the account (This name is for display only and might not be unique.)  # noqa: E501

        :param name: The name of this AccountNoId.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def capabilities(self):
        """Gets the capabilities of this AccountNoId.  # noqa: E501

        the high-level features enabled for this account, such as S3 or Swift protocols (Accounts must have the \"management\" capability if users will sign into the Tenant Manager.)  # noqa: E501

        :return: The capabilities of this AccountNoId.  # noqa: E501
        :rtype: list[str]
        """
        return self._capabilities

    @capabilities.setter
    def capabilities(self, capabilities):
        """Sets the capabilities of this AccountNoId.

        the high-level features enabled for this account, such as S3 or Swift protocols (Accounts must have the \"management\" capability if users will sign into the Tenant Manager.)  # noqa: E501

        :param capabilities: The capabilities of this AccountNoId.  # noqa: E501
        :type: list[str]
        """
        allowed_values = ["management", "s3", "swift"]  # noqa: E501
        if not set(capabilities).issubset(set(allowed_values)):
            raise ValueError(
                "Invalid values for `capabilities` [{0}], must be a subset of [{1}]"  # noqa: E501
                .format(", ".join(map(str, set(capabilities) - set(allowed_values))),  # noqa: E501
                        ", ".join(map(str, allowed_values)))
            )

        self._capabilities = capabilities

    @property
    def policy(self):
        """Gets the policy of this AccountNoId.  # noqa: E501


        :return: The policy of this AccountNoId.  # noqa: E501
        :rtype: PolicyAccount
        """
        return self._policy

    @policy.setter
    def policy(self, policy):
        """Sets the policy of this AccountNoId.


        :param policy: The policy of this AccountNoId.  # noqa: E501
        :type: PolicyAccount
        """

        self._policy = policy

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AccountNoId, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AccountNoId):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
