# coding: utf-8

"""
    StorageGRID Management API v3

    REST API for managing StorageGRID deployments. Copyright (c) 2021 NetApp, Inc. All Rights Reserved  # noqa: E501

    OpenAPI spec version: 3.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from netapp_client.models.network import Network  # noqa: F401,E501

class AdminNetwork(Network):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'subnets': 'list[str]'
    }
    if hasattr(Network, "swagger_types"):
        swagger_types.update(Network.swagger_types)

    attribute_map = {
        'subnets': 'subnets'
    }
    if hasattr(Network, "attribute_map"):
        attribute_map.update(Network.attribute_map)

    def __init__(self, subnets=None, *args, **kwargs):  # noqa: E501
        """AdminNetwork - a model defined in Swagger"""  # noqa: E501
        self._subnets = None
        self.discriminator = None
        if subnets is not None:
            self.subnets = subnets
        Network.__init__(self, *args, **kwargs)

    @property
    def subnets(self):
        """Gets the subnets of this AdminNetwork.  # noqa: E501

        destination subnetworks of the routes out of this interface in CIDR notation  # noqa: E501

        :return: The subnets of this AdminNetwork.  # noqa: E501
        :rtype: list[str]
        """
        return self._subnets

    @subnets.setter
    def subnets(self, subnets):
        """Sets the subnets of this AdminNetwork.

        destination subnetworks of the routes out of this interface in CIDR notation  # noqa: E501

        :param subnets: The subnets of this AdminNetwork.  # noqa: E501
        :type: list[str]
        """

        self._subnets = subnets

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AdminNetwork, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AdminNetwork):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
