# coding: utf-8

"""
    StorageGRID Management API v3

    REST API for managing StorageGRID deployments. Copyright (c) 2021 NetApp, Inc. All Rights Reserved  # noqa: E501

    OpenAPI spec version: 3.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class IlmPlacement(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'retention': 'Retention',
        'replicated': 'list[Replicated]',
        'erasure_coded': 'list[ErasureCoded]'
    }

    attribute_map = {
        'retention': 'retention',
        'replicated': 'replicated',
        'erasure_coded': 'erasureCoded'
    }

    def __init__(self, retention=None, replicated=None, erasure_coded=None):  # noqa: E501
        """IlmPlacement - a model defined in Swagger"""  # noqa: E501
        self._retention = None
        self._replicated = None
        self._erasure_coded = None
        self.discriminator = None
        self.retention = retention
        if replicated is not None:
            self.replicated = replicated
        if erasure_coded is not None:
            self.erasure_coded = erasure_coded

    @property
    def retention(self):
        """Gets the retention of this IlmPlacement.  # noqa: E501


        :return: The retention of this IlmPlacement.  # noqa: E501
        :rtype: Retention
        """
        return self._retention

    @retention.setter
    def retention(self, retention):
        """Sets the retention of this IlmPlacement.


        :param retention: The retention of this IlmPlacement.  # noqa: E501
        :type: Retention
        """
        if retention is None:
            raise ValueError("Invalid value for `retention`, must not be `None`")  # noqa: E501

        self._retention = retention

    @property
    def replicated(self):
        """Gets the replicated of this IlmPlacement.  # noqa: E501

        creates replicated copies of object data; otherwise, must be omitted  # noqa: E501

        :return: The replicated of this IlmPlacement.  # noqa: E501
        :rtype: list[Replicated]
        """
        return self._replicated

    @replicated.setter
    def replicated(self, replicated):
        """Sets the replicated of this IlmPlacement.

        creates replicated copies of object data; otherwise, must be omitted  # noqa: E501

        :param replicated: The replicated of this IlmPlacement.  # noqa: E501
        :type: list[Replicated]
        """

        self._replicated = replicated

    @property
    def erasure_coded(self):
        """Gets the erasure_coded of this IlmPlacement.  # noqa: E501

        creates erasure coded copies of object data; otherwise, must be omitted  # noqa: E501

        :return: The erasure_coded of this IlmPlacement.  # noqa: E501
        :rtype: list[ErasureCoded]
        """
        return self._erasure_coded

    @erasure_coded.setter
    def erasure_coded(self, erasure_coded):
        """Sets the erasure_coded of this IlmPlacement.

        creates erasure coded copies of object data; otherwise, must be omitted  # noqa: E501

        :param erasure_coded: The erasure_coded of this IlmPlacement.  # noqa: E501
        :type: list[ErasureCoded]
        """

        self._erasure_coded = erasure_coded

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IlmPlacement, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IlmPlacement):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
