# coding: utf-8

"""
    StorageGRID Management API v3

    REST API for managing StorageGRID deployments. Copyright (c) 2021 NetApp, Inc. All Rights Reserved  # noqa: E501

    OpenAPI spec version: 3.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class LocalizedError(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'text': 'str',
        'key': 'str',
        'context': 'str',
        'developer_message': 'str'
    }

    attribute_map = {
        'text': 'text',
        'key': 'key',
        'context': 'context',
        'developer_message': 'developerMessage'
    }

    def __init__(self, text=None, key=None, context=None, developer_message=None):  # noqa: E501
        """LocalizedError - a model defined in Swagger"""  # noqa: E501
        self._text = None
        self._key = None
        self._context = None
        self._developer_message = None
        self.discriminator = None
        self.text = text
        if key is not None:
            self.key = key
        if context is not None:
            self.context = context
        if developer_message is not None:
            self.developer_message = developer_message

    @property
    def text(self):
        """Gets the text of this LocalizedError.  # noqa: E501

        the localized text describing the error  # noqa: E501

        :return: The text of this LocalizedError.  # noqa: E501
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text):
        """Sets the text of this LocalizedError.

        the localized text describing the error  # noqa: E501

        :param text: The text of this LocalizedError.  # noqa: E501
        :type: str
        """
        if text is None:
            raise ValueError("Invalid value for `text`, must not be `None`")  # noqa: E501

        self._text = text

    @property
    def key(self):
        """Gets the key of this LocalizedError.  # noqa: E501

        a unique key representing the message (for programmatic use)  # noqa: E501

        :return: The key of this LocalizedError.  # noqa: E501
        :rtype: str
        """
        return self._key

    @key.setter
    def key(self, key):
        """Sets the key of this LocalizedError.

        a unique key representing the message (for programmatic use)  # noqa: E501

        :param key: The key of this LocalizedError.  # noqa: E501
        :type: str
        """

        self._key = key

    @property
    def context(self):
        """Gets the context of this LocalizedError.  # noqa: E501

        the situation or field where error was triggered  # noqa: E501

        :return: The context of this LocalizedError.  # noqa: E501
        :rtype: str
        """
        return self._context

    @context.setter
    def context(self, context):
        """Sets the context of this LocalizedError.

        the situation or field where error was triggered  # noqa: E501

        :param context: The context of this LocalizedError.  # noqa: E501
        :type: str
        """

        self._context = context

    @property
    def developer_message(self):
        """Gets the developer_message of this LocalizedError.  # noqa: E501

        additional information to aid in debugging  # noqa: E501

        :return: The developer_message of this LocalizedError.  # noqa: E501
        :rtype: str
        """
        return self._developer_message

    @developer_message.setter
    def developer_message(self, developer_message):
        """Sets the developer_message of this LocalizedError.

        additional information to aid in debugging  # noqa: E501

        :param developer_message: The developer_message of this LocalizedError.  # noqa: E501
        :type: str
        """

        self._developer_message = developer_message

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LocalizedError, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LocalizedError):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
