# coding: utf-8

"""
    StorageGRID Management API v3

    REST API for managing StorageGRID deployments. Copyright (c) 2021 NetApp, Inc. All Rights Reserved  # noqa: E501

    OpenAPI spec version: 3.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class OriginalProperties(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'enable': 'bool',
        'expressions': 'AllOfOriginalPropertiesExpressions',
        '_for': 'str'
    }

    attribute_map = {
        'enable': 'enable',
        'expressions': 'expressions',
        '_for': 'for'
    }

    def __init__(self, enable=None, expressions=None, _for=None):  # noqa: E501
        """OriginalProperties - a model defined in Swagger"""  # noqa: E501
        self._enable = None
        self._expressions = None
        self.__for = None
        self.discriminator = None
        if enable is not None:
            self.enable = enable
        if expressions is not None:
            self.expressions = expressions
        if _for is not None:
            self._for = _for

    @property
    def enable(self):
        """Gets the enable of this OriginalProperties.  # noqa: E501

        whether this alert rule is enabled  # noqa: E501

        :return: The enable of this OriginalProperties.  # noqa: E501
        :rtype: bool
        """
        return self._enable

    @enable.setter
    def enable(self, enable):
        """Sets the enable of this OriginalProperties.

        whether this alert rule is enabled  # noqa: E501

        :param enable: The enable of this OriginalProperties.  # noqa: E501
        :type: bool
        """

        self._enable = enable

    @property
    def expressions(self):
        """Gets the expressions of this OriginalProperties.  # noqa: E501


        :return: The expressions of this OriginalProperties.  # noqa: E501
        :rtype: AllOfOriginalPropertiesExpressions
        """
        return self._expressions

    @expressions.setter
    def expressions(self, expressions):
        """Sets the expressions of this OriginalProperties.


        :param expressions: The expressions of this OriginalProperties.  # noqa: E501
        :type: AllOfOriginalPropertiesExpressions
        """

        self._expressions = expressions

    @property
    def _for(self):
        """Gets the _for of this OriginalProperties.  # noqa: E501

        how long one or more of the expressions in this rule must evaluate as true before an alert is generated  # noqa: E501

        :return: The _for of this OriginalProperties.  # noqa: E501
        :rtype: str
        """
        return self.__for

    @_for.setter
    def _for(self, _for):
        """Sets the _for of this OriginalProperties.

        how long one or more of the expressions in this rule must evaluate as true before an alert is generated  # noqa: E501

        :param _for: The _for of this OriginalProperties.  # noqa: E501
        :type: str
        """

        self.__for = _for

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OriginalProperties, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OriginalProperties):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
