# coding: utf-8

"""
    StorageGRID Management API v3

    REST API for managing StorageGRID deployments. Copyright (c) 2021 NetApp, Inc. All Rights Reserved  # noqa: E501

    OpenAPI spec version: 3.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from swagger_client.models.permissions_list_except_root import PermissionsListExceptRoot  # noqa: F401,E501

class PolicyManagement(PermissionsListExceptRoot):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'root_access': 'bool'
    }
    if hasattr(PermissionsListExceptRoot, "swagger_types"):
        swagger_types.update(PermissionsListExceptRoot.swagger_types)

    attribute_map = {
        'root_access': 'rootAccess'
    }
    if hasattr(PermissionsListExceptRoot, "attribute_map"):
        attribute_map.update(PermissionsListExceptRoot.attribute_map)

    def __init__(self, root_access=None, *args, **kwargs):  # noqa: E501
        """PolicyManagement - a model defined in Swagger"""  # noqa: E501
        self._root_access = None
        self.discriminator = None
        if root_access is not None:
            self.root_access = root_access
        PermissionsListExceptRoot.__init__(self, *args, **kwargs)

    @property
    def root_access(self):
        """Gets the root_access of this PolicyManagement.  # noqa: E501

        full access to all grid administration features  # noqa: E501

        :return: The root_access of this PolicyManagement.  # noqa: E501
        :rtype: bool
        """
        return self._root_access

    @root_access.setter
    def root_access(self, root_access):
        """Sets the root_access of this PolicyManagement.

        full access to all grid administration features  # noqa: E501

        :param root_access: The root_access of this PolicyManagement.  # noqa: E501
        :type: bool
        """

        self._root_access = root_access

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PolicyManagement, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PolicyManagement):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
